from gym.envs.registration import register as gym_register

env_list = []

def register(
    id,
    grid_size,
    max_steps,
    local_step_num,
    agent_view_size,
    num_obstacles,
    max_num_targets,
    num_agents,
    n_agent_types,
    agent_classes_list,
    agent_pos,
    entry_point,
    reward_threshold=0.95,
    use_full_comm=False,
    use_partial_comm=False,
    use_orientation = False,
    use_same_location = True,
    use_agent_obstacle = False,
    use_time_penalty = False,
    use_energy_penalty = False,
    use_auxiliary_rewards = False,
    use_auxiliary_rewards_decay = True,
    max_auxiliary_reward_episode = 2000,
    algorithm_name = 'amat',
    comm_sigma = 5,
    comm_radius = 10,
    block_doors = False,
    block_chance = 0.25,
    use_slam_noise = False,
    slam_noise_prob = 0.05,
    use_perception_noise = False,
    perception_noise_base_value = 0.1,
    perception_noise_distance_factor = 0.05,
    action_size = 5,
    dynamic_targets = False,
    target_behavior = 'default',
    dynamic_obstacles = False,
    obstacle_behavior = 'oscillate',
    spawn_hazards = False,
    max_num_hazards = 5,
    exploration_only = False,
):
    assert id.startswith("MiniGrid-")
    # assert id not in env_list

    # Register the environment with OpenAI gym
    gym_register(
        id=id,
        entry_point=entry_point,
        kwargs={
        'grid_size': grid_size,
        'max_steps': max_steps,
        'local_step_num': local_step_num,
        'agent_view_size': agent_view_size,
        'num_obstacles': num_obstacles,
        'max_num_targets': max_num_targets,
        'num_agents': num_agents,
        'n_agent_types': n_agent_types,
        'agent_classes_list' : agent_classes_list,
        'agent_pos': agent_pos,
        'use_full_comm': use_full_comm,
        'use_partial_comm': use_partial_comm,
        'use_orientation':use_orientation,
        'use_same_location': use_same_location,
        'use_agent_obstacle': use_agent_obstacle,
        'use_time_penalty': use_time_penalty,
        'use_energy_penalty': use_energy_penalty,
        'use_auxiliary_rewards': use_auxiliary_rewards,
        'use_auxiliary_rewards_decay': use_auxiliary_rewards_decay,
        'max_auxiliary_reward_episode': max_auxiliary_reward_episode,
        'algorithm_name': algorithm_name,
        'comm_sigma': comm_sigma,
        'comm_radius': comm_radius,
        'block_doors': block_doors,
        'block_chance': block_chance,
        'use_slam_noise': use_slam_noise,
        'slam_noise_prob': slam_noise_prob,
        'use_perception_noise': use_perception_noise,
        'perception_noise_base_value': perception_noise_base_value,
        'perception_noise_distance_factor': perception_noise_distance_factor,
        'action_size': action_size,
        'dynamic_targets': dynamic_targets,
        'target_behavior': target_behavior,
        'dynamic_obstacles': dynamic_obstacles,
        'obstacle_behavior': obstacle_behavior,
        'spawn_hazards': spawn_hazards,
        'max_num_hazards': max_num_hazards,
        'exploration_only': exploration_only,
        },
        reward_threshold=reward_threshold
    )

    # Add the environment to the set
    env_list.append(id)
